version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017
      PRIVACY_BUDGET: 10.0
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  mongodb_data: